// flow-typed signature: 68011f2b781889260c14dd881914ebfb
// flow-typed version: <<STUB>>/cosmiconfig_v^4.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cosmiconfig'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cosmiconfig' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cosmiconfig/dist/createExplorer' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/funcRunner' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/getDirectory' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/index' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/loadDefinedFile' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/loadJs' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/loadPackageProp' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/loadRc' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/parseJson' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/readFile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cosmiconfig/dist/createExplorer.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/createExplorer'>;
}
declare module 'cosmiconfig/dist/funcRunner.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/funcRunner'>;
}
declare module 'cosmiconfig/dist/getDirectory.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/getDirectory'>;
}
declare module 'cosmiconfig/dist/index.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/index'>;
}
declare module 'cosmiconfig/dist/loadDefinedFile.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/loadDefinedFile'>;
}
declare module 'cosmiconfig/dist/loadJs.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/loadJs'>;
}
declare module 'cosmiconfig/dist/loadPackageProp.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/loadPackageProp'>;
}
declare module 'cosmiconfig/dist/loadRc.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/loadRc'>;
}
declare module 'cosmiconfig/dist/parseJson.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/parseJson'>;
}
declare module 'cosmiconfig/dist/readFile.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/readFile'>;
}
