// flow-typed signature: 2ffc323e15187a7c0d04f1e9263f449d
// flow-typed version: <<STUB>>/jest-snapshot-serializer-function-name_v^1.1.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-snapshot-serializer-function-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-snapshot-serializer-function-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-snapshot-serializer-function-name/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-snapshot-serializer-function-name/index' {
  declare module.exports: $Exports<'jest-snapshot-serializer-function-name'>;
}
declare module 'jest-snapshot-serializer-function-name/index.js' {
  declare module.exports: $Exports<'jest-snapshot-serializer-function-name'>;
}
declare module 'jest-snapshot-serializer-function-name/index.test.js' {
  declare module.exports: $Exports<'jest-snapshot-serializer-function-name/index.test'>;
}
