// flow-typed signature: 1e0867d457cec37e7590c556b0fbfb2f
// flow-typed version: <<STUB>>/parent-module_v^0.1.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parent-module'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parent-module' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'parent-module/index' {
  declare module.exports: $Exports<'parent-module'>;
}
declare module 'parent-module/index.js' {
  declare module.exports: $Exports<'parent-module'>;
}
