// flow-typed signature: 31b8a3f0da6fc500c0df4a0bcc479d8d
// flow-typed version: <<STUB>>/sort-keys_v^2.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sort-keys'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sort-keys' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'sort-keys/index' {
  declare module.exports: $Exports<'sort-keys'>;
}
declare module 'sort-keys/index.js' {
  declare module.exports: $Exports<'sort-keys'>;
}
