// flow-typed signature: 1ed8340c62aa9ecbb3570185cc8e4254
// flow-typed version: <<STUB>>/@chrisblossom/eslint-config_v^2.0.6/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@chrisblossom/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@chrisblossom/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@chrisblossom/eslint-config/eslint-config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@chrisblossom/eslint-config/eslint-config.js' {
  declare module.exports: $Exports<'@chrisblossom/eslint-config/eslint-config'>;
}
